"use client";
import { ChangeEvent, useEffect, useRef, useState } from "react";
import Link from "next/link";
import NextImage from "next/image";
import Cropper, { Area } from "react-easy-crop";
import { toJpeg, toPng } from "html-to-image";
import { Check, ChevronLeft, Download, ImagePlus, LayoutTemplate, Moon, Palette, Plus, RotateCcw, Sparkles, Sun, Trash2, Type, Upload, X } from "lucide-react";
import { Template, templates } from "@/data/templates";
import { fonts } from "@/data/fonts";
import { Button } from "@/components/ui/Button";
import { DesignCanvas, DesignState } from "./DesignCanvas";
import { getCroppedImage } from "./cropImage";
import pelindoLogo from "@/assets/pelindo.png";

type Tab="template"|"photo"|"text"|"style"|"export";
const DEFAULT:DesignState={template:templates[0],photo:null,title:"Selamat Ulang Tahun",name:"INSAN PELINDO",message:"Semoga sehat selalu, panjang umur, dan sukses dalam setiap langkah.",titleFont:"Great Vibes",nameFont:"Montserrat",titleColor:"#ffffff",nameColor:"#f6c453",accent:"#00c2ff",titleSize:62,nameSize:34,messageSize:14,textShadow:true,glow:true,photoScale:1,photoX:0,photoY:0,photoRotation:0,frame:"arch",frameShadow:true,frameX:50,frameY:47.5,frameWidth:47,frameHeight:37,nameX:50,nameY:74,titleX:50,titleY:16,customTexts:[],logo:null,logoX:85,logoY:12,logoWidth:16,messageStyle:"glass"};
const nav=[{id:"template",label:"Template",Icon:LayoutTemplate},{id:"photo",label:"Foto",Icon:ImagePlus},{id:"text",label:"Teks",Icon:Type},{id:"style",label:"Gaya",Icon:Palette},{id:"export",label:"Export",Icon:Download}] as const;

export default function Editor(){
  const [tab,setTab]=useState<Tab>("template"),[state,setState]=useState(DEFAULT),[raw,setRaw]=useState<string|null>(null),[crop,setCrop]=useState({x:0,y:0}),[zoom,setZoom]=useState(1),[rotation,setRotation]=useState(0),[area,setArea]=useState<Area|null>(null),[exporting,setExporting]=useState(false);
  const [theme,setTheme]=useState<"light"|"dark">("light");
  const canvasRef=useRef<HTMLDivElement>(null); const set=<K extends keyof DesignState>(key:K,value:DesignState[K])=>setState(s=>({...s,[key]:value}));
  useEffect(()=>{const saved=localStorage.getItem("birthday-studio-theme");if(saved==="dark"||saved==="light")queueMicrotask(()=>setTheme(saved))},[]);
  const toggleTheme=()=>setTheme(current=>{const next=current==="light"?"dark":"light";localStorage.setItem("birthday-studio-theme",next);document.documentElement.dataset.theme=next;return next});
  const upload=(e:ChangeEvent<HTMLInputElement>)=>{const file=e.target.files?.[0];if(!file)return;if(file.size>10_000_000){alert("Ukuran foto maksimal 10 MB");return}const reader=new FileReader();reader.onload=()=>setRaw(String(reader.result));reader.readAsDataURL(file)};
  const uploadLogo=(e:ChangeEvent<HTMLInputElement>)=>{const file=e.target.files?.[0];if(!file)return;if(file.size>5_000_000){alert("Ukuran logo maksimal 5 MB");return}const reader=new FileReader();reader.onload=()=>set("logo",String(reader.result));reader.readAsDataURL(file)};
  const uploadTemplate=(e:ChangeEvent<HTMLInputElement>)=>{const file=e.target.files?.[0];if(!file)return;if(file.size>15_000_000){alert("Ukuran template maksimal 15 MB");return}const reader=new FileReader();reader.onload=()=>{const src=String(reader.result);const image=new Image();image.onload=()=>{const custom:Template={id:`custom-${Date.now()}`,name:file.name,eyebrow:"Template sendiri",accent:"#00c2ff",tone:"dark",image:src,background:"#061b33",width:image.naturalWidth,height:image.naturalHeight};set("template",custom)};image.src=src};reader.readAsDataURL(file)};
  const moveCustomText=(id:string,x:number,y:number)=>setState(current=>({...current,customTexts:current.customTexts.map(item=>item.id===id?{...item,x,y}:item)}));
  const moveFrame=(x:number,y:number)=>setState(current=>({...current,frameX:x,frameY:y}));
  const transformFrame=(x:number,y:number,frameWidth:number,frameHeight:number)=>setState(current=>({...current,frameX:x,frameY:y,frameWidth,frameHeight}));
  const moveName=(x:number,y:number)=>setState(current=>({...current,nameX:x,nameY:y}));
  const moveTitle=(x:number,y:number)=>setState(current=>({...current,titleX:x,titleY:y}));
  const moveLogo=(x:number,y:number)=>setState(current=>({...current,logoX:x,logoY:y}));
  const resizeLogo=(logoWidth:number)=>setState(current=>({...current,logoWidth}));
  const applyCrop=async()=>{if(raw&&area){set("photo",await getCroppedImage(raw,area,rotation));setRaw(null);setCrop({x:0,y:0});setZoom(1);setRotation(0)}};
  const exportDesign=async(format:"png"|"jpg")=>{if(!canvasRef.current)return;setExporting(true);try{await document.fonts.ready;const {width,height}=state.template;const options={canvasWidth:width,canvasHeight:height,pixelRatio:1,cacheBust:true,filter:(node:HTMLElement)=>!node.hasAttribute?.("data-export-ignore")};const url=format==="png"?await toPng(canvasRef.current,options):await toJpeg(canvasRef.current,{...options,quality:.95,backgroundColor:"#061b33"});const a=document.createElement("a");a.download=`pelindo-birthday-${state.name.toLowerCase().replace(/[^a-z0-9]+/g,"-")||"design"}.${format}`;a.href=url;a.click()}finally{setExporting(false)}};
  return <main className={`clay-app min-h-screen bg-[#03101e] text-slate-100 ${theme==="dark"?"clay-dark":""}`}>
    <header className="flex h-[76px] items-center justify-between gap-5 border-b border-white/10 bg-[#061b33]/95 px-5 sm:px-7"><div className="flex items-center gap-4"><Link href="/" aria-label="Kembali" className="rounded-xl border border-white/10 p-2 hover:bg-white/10"><ChevronLeft size={19}/></Link><span className="editor-brand-logo pelindo-brand-mark grid size-10 place-items-center rounded-xl"><NextImage src={pelindoLogo} alt="Logo Pelindo" className="size-7 object-contain"/></span><div className="editor-brand-copy ml-1"><b className="text-sm tracking-wide">Birthday Studio</b><p className="text-[9px] tracking-[.2em] text-[#168ed1]">PELINDO CREATIVE TOOLS</p></div></div><div className="hidden items-center gap-2 text-xs text-[#5f7f98] sm:flex"><span className="size-2 rounded-full bg-emerald-500"/>Tersimpan di perangkat</div><div className="flex items-center gap-3"><button onClick={toggleTheme} aria-label={theme==="light"?"Aktifkan dark mode":"Aktifkan light mode"} title={theme==="light"?"Dark mode":"Light mode"} className="theme-toggle grid size-11 place-items-center rounded-2xl transition hover:-translate-y-0.5">{theme==="light"?<Moon size={19}/>:<Sun size={20}/>}</button><Button onClick={()=>exportDesign("png")} disabled={exporting} className="clay-primary flex items-center gap-2 px-5"><Download size={16}/><span className="hidden sm:inline">{exporting?"Menyiapkan...":"Download"}</span></Button></div></header>
    <div className="grid min-h-[calc(100vh-72px)] lg:grid-cols-[88px_330px_1fr]">
      <aside className="editor-tools-nav no-scrollbar order-2 flex overflow-x-auto border-t border-white/10 bg-[#061526] lg:order-none lg:flex-col lg:border-r lg:border-t-0">{nav.map(({id,label,Icon})=><button key={id} onClick={()=>setTab(id)} className={`relative flex min-w-[76px] flex-1 flex-col items-center gap-2 px-2 py-4 text-[10px] transition lg:flex-none lg:py-5 ${tab===id?"bg-cyan-300/10 text-cyan-300":"text-slate-500 hover:bg-white/5 hover:text-slate-200"}`}>{tab===id&&<span className="absolute left-0 top-1/4 hidden h-1/2 w-[3px] rounded-r bg-cyan-300 lg:block"/>}<Icon size={21}/>{label}</button>)}</aside>
      <aside className="order-3 max-h-[48vh] overflow-y-auto border-t border-white/10 bg-[#07192d] p-5 lg:order-none lg:max-h-[calc(100vh-72px)] lg:border-r lg:border-t-0 lg:p-6"><Panel tab={tab} state={state} set={set} upload={upload} uploadLogo={uploadLogo} uploadTemplate={uploadTemplate} reset={()=>setState(DEFAULT)} exportDesign={exportDesign} exporting={exporting}/></aside>
      <section className="grid-bg order-1 grid min-h-[55vh] place-items-center overflow-hidden bg-[#04111f] p-5 sm:p-8 lg:order-none lg:min-h-0"><div className={`w-full ${state.template.width>state.template.height?"max-w-[760px]":"max-w-[430px]"}`}><div className="mb-3 flex items-center justify-between text-[10px] uppercase tracking-[.18em] text-slate-500"><span>Preview {state.template.width>state.template.height?"Landscape":"Portrait"}</span><span>{state.template.width} × {state.template.height} px</span></div><div className="canvas-shadow overflow-hidden rounded-lg"><DesignCanvas ref={canvasRef} state={state} onCustomTextMove={moveCustomText} onFrameMove={moveFrame} onFrameTransform={transformFrame} onNameMove={moveName} onTitleMove={moveTitle} onLogoMove={moveLogo} onLogoResize={resizeLogo}/></div></div></section>
    </div>
    {raw&&<div className="fixed inset-0 z-50 grid place-items-center bg-black/80 p-4 backdrop-blur-sm"><div className="w-full max-w-2xl overflow-hidden rounded-3xl border border-white/15 bg-[#07192d] shadow-2xl"><div className="flex items-center justify-between border-b border-white/10 p-5"><div><b>Atur foto</b><p className="text-xs text-slate-400">Geser, perbesar, atau putar foto</p></div><button onClick={()=>setRaw(null)} className="rounded-lg p-2 hover:bg-white/10"><X/></button></div><div className="relative h-[440px] bg-black"><Cropper image={raw} crop={crop} zoom={zoom} rotation={rotation} aspect={4/5} onCropChange={setCrop} onZoomChange={setZoom} onRotationChange={setRotation} onCropComplete={(_,pixels)=>setArea(pixels)}/></div><div className="flex flex-col gap-4 p-5 sm:flex-row sm:items-end"><Range label="Zoom" value={zoom} min={1} max={3} step={.05} onChange={setZoom}/><Range label="Rotasi" value={rotation} min={-180} max={180} step={1} onChange={setRotation}/><Button onClick={applyCrop} className="flex shrink-0 items-center justify-center gap-2 bg-[#0077c8]"><Check size={16}/>Terapkan foto</Button></div></div></div>}
  </main>;
}

function Panel({tab,state,set,upload,uploadLogo,uploadTemplate,reset,exportDesign,exporting}:{tab:Tab;state:DesignState;set:<K extends keyof DesignState>(k:K,v:DesignState[K])=>void;upload:(e:ChangeEvent<HTMLInputElement>)=>void;uploadLogo:(e:ChangeEvent<HTMLInputElement>)=>void;uploadTemplate:(e:ChangeEvent<HTMLInputElement>)=>void;reset:()=>void;exportDesign:(f:"png"|"jpg")=>void;exporting:boolean}){
 const title={template:"Pilih template",photo:"Foto utama",text:"Konten ucapan",style:"Gaya desain",export:"Unduh desain"}[tab];
 return <><div className="mb-6"><p className="text-[10px] font-semibold uppercase tracking-[.22em] text-cyan-300">Editor</p><h2 className="mt-1 text-xl font-semibold">{title}</h2></div>
 {tab==="template"&&<div className="space-y-7">
   <section>
     <SectionTitle title="Template Anda" description="Desain resmi yang Anda tambahkan ke project"/>
     <div className="space-y-4">{templates.filter(t=>t.id.startsWith("pelindo-")).map(t=><TemplateCard key={t.id} t={t} state={state} set={set}/>)}</div>
   </section>
   <section className="border-t border-white/10 pt-6">
     <SectionTitle title="Upload Template Baru" description="Tambahkan desain lain dari perangkat"/>
     <label className="flex cursor-pointer items-center gap-3 rounded-2xl border border-dashed border-cyan-300/35 bg-cyan-300/5 p-4 hover:bg-cyan-300/10"><span className="grid size-10 place-items-center rounded-xl bg-cyan-300/10 text-cyan-300"><Upload size={18}/></span><span><b className="block text-sm">Pilih file template</b><small className="text-slate-500">PNG, JPG, atau WebP • semua rasio</small></span><input type="file" accept="image/png,image/jpeg,image/webp" onChange={uploadTemplate} className="hidden"/></label>
     {state.template.id.startsWith("custom-")&&<div className="mt-4"><TemplateCard t={state.template} state={state} set={set}/></div>}
   </section>
   <section className="border-t border-white/10 pt-6">
     <SectionTitle title="Template Custom" description="Background custom dari Birthday Studio"/>
     <div className="space-y-4">{templates.filter(t=>!t.id.startsWith("pelindo-")).map(t=><TemplateCard key={t.id} t={t} state={state} set={set}/>)}</div>
   </section>
 </div>}
 {tab==="photo"&&<div className="space-y-5"><label className="flex cursor-pointer flex-col items-center rounded-2xl border border-dashed border-cyan-300/35 bg-cyan-300/5 px-4 py-8 text-center hover:bg-cyan-300/10"><Upload className="mb-3 text-cyan-300"/><b className="text-sm">{state.photo?"Ganti & crop foto":"Upload & crop foto"}</b><span className="mt-1 text-xs text-slate-500">JPG atau PNG, maks. 10 MB</span><input type="file" accept="image/png,image/jpeg,image/webp" onChange={upload} className="hidden"/></label><div className="rounded-xl border border-cyan-300/15 bg-cyan-300/5 px-3 py-2 text-[10px] leading-4 text-cyan-200">Drag frame foto langsung pada preview untuk memindahkannya.</div>{state.photo&&<><Range label="Skala foto dalam frame" value={state.photoScale} min={.8} max={2} step={.05} onChange={v=>set("photoScale",v)}/><Range label="Posisi foto horizontal" value={state.photoX} min={-80} max={80} step={1} onChange={v=>set("photoX",v)}/><Range label="Posisi foto vertikal" value={state.photoY} min={-80} max={80} step={1} onChange={v=>set("photoY",v)}/><Range label="Rotasi foto" value={state.photoRotation} min={-30} max={30} step={1} onChange={v=>set("photoRotation",v)}/><button onClick={()=>set("photo",null)} className="w-full rounded-xl border border-red-400/20 py-3 text-sm text-red-300 hover:bg-red-400/10">Hapus foto</button></>}<section className="border-t border-white/10 pt-6"><div className="mb-3"><h3 className="text-sm font-semibold">Logo</h3><p className="mt-1 text-[10px] text-slate-500">Tambahkan logo organisasi atau unit kerja</p></div><label className="flex cursor-pointer items-center gap-3 rounded-2xl border border-dashed border-cyan-300/35 bg-cyan-300/5 p-4 hover:bg-cyan-300/10"><span className="grid size-10 place-items-center rounded-xl bg-cyan-300/10 text-cyan-300"><Upload size={18}/></span><span><b className="block text-sm">{state.logo?"Ganti logo":"Upload logo"}</b><small className="text-slate-500">PNG transparan disarankan • maks. 5 MB</small></span><input type="file" accept="image/png,image/jpeg,image/webp" onChange={uploadLogo} className="hidden"/></label>{state.logo&&<><div className="mt-3 rounded-xl border border-cyan-300/15 bg-cyan-300/5 px-3 py-2 text-[10px] leading-4 text-cyan-200">Drag logo untuk memindahkan. Tarik titik sudut untuk mengubah ukuran.</div><button onClick={()=>set("logo",null)} className="mt-3 w-full rounded-xl border border-red-400/20 py-3 text-sm text-red-300 hover:bg-red-400/10">Hapus logo</button></>}</section></div>}
 {tab==="text"&&<div className="space-y-5"><Field label="Judul"><textarea value={state.title} onChange={e=>set("title",e.target.value)} maxLength={64} rows={3}/><span className="mt-1 block text-[10px] text-slate-500">Shift + Enter untuk membuat baris baru</span></Field><div className="rounded-xl border border-cyan-300/15 bg-cyan-300/5 px-3 py-2 text-[10px] leading-4 text-cyan-200">Drag judul langsung pada preview untuk memindahkan posisinya.</div><Field label="Nama"><input value={state.name} onChange={e=>set("name",e.target.value)} maxLength={28}/></Field><div className="rounded-xl border border-cyan-300/15 bg-cyan-300/5 px-3 py-2 text-[10px] leading-4 text-cyan-200">Drag nama langsung pada preview untuk memindahkan posisinya.</div><Field label="Doa & harapan"><textarea value={state.message} onChange={e=>set("message",e.target.value)} maxLength={140} rows={4}/><span className="mt-1 block text-right text-[10px] text-slate-500">{state.message.length}/140</span></Field><MessageStylePicker value={state.messageStyle} onChange={value=>set("messageStyle",value)}/><Range label="Ukuran judul" value={state.titleSize} min={36} max={82} step={1} onChange={v=>set("titleSize",v)}/><Range label="Ukuran nama" value={state.nameSize} min={22} max={48} step={1} onChange={v=>set("nameSize",v)}/><Range label="Ukuran pesan" value={state.messageSize} min={10} max={20} step={1} onChange={v=>set("messageSize",v)}/><CustomTextEditor state={state} set={set}/></div>}
 {tab==="style"&&<div className="space-y-6"><Field label="Font judul"><select value={state.titleFont} onChange={e=>set("titleFont",e.target.value)}>{fonts.map(f=><option key={f}>{f}</option>)}</select></Field><Field label="Font nama"><select value={state.nameFont} onChange={e=>set("nameFont",e.target.value)}>{fonts.map(f=><option key={f}>{f}</option>)}</select></Field><div className="grid grid-cols-3 gap-3"><Color label="Judul" value={state.titleColor} onChange={v=>set("titleColor",v)}/><Color label="Nama" value={state.nameColor} onChange={v=>set("nameColor",v)}/><Color label="Aksen" value={state.accent} onChange={v=>set("accent",v)}/></div><div><Label>Bentuk frame</Label><div className="grid grid-cols-2 gap-2">{(["none","circle","arch","rounded"] as const).map(f=><button key={f} onClick={()=>set("frame",f)} className={`rounded-xl border px-2 py-3 text-xs capitalize ${state.frame===f?"border-cyan-300 bg-cyan-300/10 text-cyan-200":"border-white/10 text-slate-400"}`}>{f==="none"?"Tanpa Frame":f}</button>)}</div></div><Toggle label="Shadow teks" value={state.textShadow} onChange={v=>set("textShadow",v)}/><Toggle label="Glow judul" value={state.glow} onChange={v=>set("glow",v)}/>{state.frame!=="none"&&<Toggle label="Shadow foto" value={state.frameShadow} onChange={v=>set("frameShadow",v)}/>}</div>}
 {tab==="export"&&<div className="space-y-4"><div className="rounded-2xl border border-cyan-300/15 bg-cyan-300/5 p-5"><Sparkles className="mb-4 text-cyan-300"/><b className="block">Siap dibagikan</b><p className="mt-2 text-xs leading-6 text-slate-400">Hasil berukuran {state.template.width} × {state.template.height} px, mengikuti ukuran asli template yang dipilih.</p></div><Button disabled={exporting} onClick={()=>exportDesign("png")} className="flex w-full items-center justify-center gap-2 bg-[#0077c8]"><Download size={17}/>Download PNG</Button><Button disabled={exporting} onClick={()=>exportDesign("jpg")} className="flex w-full items-center justify-center gap-2 border border-white/15 bg-white/5"><Download size={17}/>Download JPG</Button><button onClick={reset} className="flex w-full items-center justify-center gap-2 py-3 text-xs text-slate-500 hover:text-white"><RotateCcw size={14}/>Reset semua desain</button></div>}
 </>;
}
function TemplateCard({t,state,set}:{t:Template;state:DesignState;set:<K extends keyof DesignState>(k:K,v:DesignState[K])=>void}){
 const select=()=>{set("template",t);set("accent",t.accent);set("titleColor",t.tone==="light"?"#005bac":"#ffffff");set("nameColor",t.tone==="light"?"#06335b":"#f6c453")};
 return <button onClick={select} className={`w-full overflow-hidden rounded-2xl border text-left transition ${state.template.id===t.id?"border-cyan-300 ring-2 ring-cyan-300/15":"border-white/10 hover:border-white/30"}`}><div className="h-28 bg-cover bg-center" style={{background:t.image?`url(${t.image}) center/cover`:t.background}}/><div className="flex items-center justify-between bg-white/5 px-4 py-3"><span className="min-w-0"><b className="block truncate text-sm">{t.name}</b><small className="text-slate-500">{t.eyebrow}</small></span>{state.template.id===t.id&&<Check className="shrink-0 text-cyan-300" size={18}/>}</div></button>;
}
function MessageStylePicker({value,onChange}:{value:DesignState["messageStyle"];onChange:(value:DesignState["messageStyle"])=>void}){
 const styles:[DesignState["messageStyle"],string,string][]=[["glass","Glass","bg-[#0b2944]/75 border-white/20 backdrop-blur"],["gold","Gold Premium","bg-gradient-to-br from-[#26323a] to-[#081522] border-[#f6c453]"],["minimal","Minimal Line","border-x-0 border-y border-cyan-400 bg-transparent rounded-none"],["soft","Soft Card","bg-[#edf8ff] border-white text-[#06335b]"]];
 return <div><Label>Gaya kartu doa</Label><div className="grid grid-cols-2 gap-3">{styles.map(([id,label,preview])=><button type="button" key={id} onClick={()=>onChange(id)} className={`rounded-2xl border p-2.5 text-left transition ${value===id?"border-cyan-400 bg-cyan-300/10 ring-2 ring-cyan-300/15":"border-white/10 bg-white/[.025]"}`}><div className={`mb-2 grid h-12 place-items-center rounded-xl border px-2 ${preview}`}><span className="h-1 w-3/4 rounded-full bg-current opacity-45"/></div><span className="text-[10px] font-semibold">{label}</span>{value===id&&<Check className="float-right text-cyan-400" size={13}/>}</button>)}</div></div>;
}
function CustomTextEditor({state,set}:{state:DesignState;set:<K extends keyof DesignState>(k:K,v:DesignState[K])=>void}){
 const add=()=>set("customTexts",[...state.customTexts,{id:`text-${Date.now()}`,text:"Teks baru",font:"Poppins",color:"#ffffff",size:24,x:50,y:50}]);
 const update=(id:string,patch:Partial<DesignState["customTexts"][number]>)=>set("customTexts",state.customTexts.map(item=>item.id===id?{...item,...patch}:item));
 const remove=(id:string)=>set("customTexts",state.customTexts.filter(item=>item.id!==id));
 return <section className="border-t border-white/10 pt-6">
   <div className="mb-4 flex items-center justify-between"><div><h3 className="text-sm font-semibold">Teks tambahan</h3><p className="mt-1 text-[10px] text-slate-500">Drag teks langsung pada preview</p></div><button onClick={add} className="flex items-center gap-1.5 rounded-xl bg-cyan-300/10 px-3 py-2 text-xs font-semibold text-cyan-300 hover:bg-cyan-300/20"><Plus size={15}/> Add text</button></div>
   {state.customTexts.length===0?<button onClick={add} className="w-full rounded-2xl border border-dashed border-white/15 px-4 py-6 text-xs text-slate-500 hover:border-cyan-300/35 hover:text-cyan-300"><Plus className="mx-auto mb-2" size={20}/>Belum ada teks tambahan</button>:<div className="space-y-4">{state.customTexts.map((item,index)=><div key={item.id} className="rounded-2xl border border-white/10 bg-white/[.035] p-4"><div className="mb-4 flex items-center justify-between"><span className="text-[10px] font-semibold uppercase tracking-wider text-cyan-300">Teks {index+1}</span><button onClick={()=>remove(item.id)} aria-label="Hapus teks" className="rounded-lg p-1.5 text-slate-500 hover:bg-red-400/10 hover:text-red-300"><Trash2 size={15}/></button></div><div className="space-y-4"><Field label="Isi teks"><textarea rows={2} value={item.text} onChange={e=>update(item.id,{text:e.target.value})} maxLength={80}/></Field><Field label="Font"><select value={item.font} onChange={e=>update(item.id,{font:e.target.value})}>{fonts.map(font=><option key={font}>{font}</option>)}</select></Field><div className="flex items-center justify-between"><Label>Warna teks</Label><input type="color" value={item.color} onChange={e=>update(item.id,{color:e.target.value})} className="h-8 w-12 cursor-pointer rounded-lg border-0 bg-transparent"/></div><Range label="Ukuran" value={item.size} min={10} max={64} step={1} onChange={size=>update(item.id,{size})}/><div className="rounded-xl border border-cyan-300/15 bg-cyan-300/5 px-3 py-2 text-[10px] leading-4 text-cyan-200">Klik dan drag teks pada preview untuk memindahkan posisinya.</div></div></div>)}</div>}
 </section>;
}
function SectionTitle({title,description}:{title:string;description:string}){return <div className="mb-3"><div className="flex items-center gap-2"><span className="h-1.5 w-1.5 rounded-full bg-cyan-300"/><h3 className="text-xs font-semibold uppercase tracking-[.13em] text-slate-200">{title}</h3></div><p className="mt-1 pl-3.5 text-[10px] leading-4 text-slate-500">{description}</p></div>}
function Label({children}:{children:React.ReactNode}){return <label className="mb-2 block text-xs font-medium text-slate-400">{children}</label>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <div><Label>{label}</Label><div className="[&_input]:w-full [&_input]:rounded-xl [&_input]:border [&_input]:border-white/10 [&_input]:bg-white/5 [&_input]:px-3 [&_input]:py-3 [&_select]:w-full [&_select]:rounded-xl [&_select]:border [&_select]:border-white/10 [&_select]:bg-[#0b2540] [&_select]:px-3 [&_select]:py-3 [&_textarea]:w-full [&_textarea]:resize-none [&_textarea]:rounded-xl [&_textarea]:border [&_textarea]:border-white/10 [&_textarea]:bg-white/5 [&_textarea]:px-3 [&_textarea]:py-3 [&_input:focus]:border-cyan-300/50 [&_input]:outline-none [&_textarea]:outline-none">{children}</div></div>}
function Range({label,value,min,max,step,onChange}:{label:string;value:number;min:number;max:number;step:number;onChange:(v:number)=>void}){return <div className="min-w-32 flex-1"><div className="mb-2 flex justify-between text-xs text-slate-400"><span>{label}</span><span className="text-slate-200">{Math.round(value*100)/100}</span></div><input className="w-full" type="range" value={value} min={min} max={max} step={step} onChange={e=>onChange(Number(e.target.value))}/></div>}
function Color({label,value,onChange}:{label:string;value:string;onChange:(v:string)=>void}){return <label className="text-center text-[10px] text-slate-400"><span className="mx-auto mb-2 block size-10 overflow-hidden rounded-xl border border-white/15" style={{background:value}}><input type="color" value={value} onChange={e=>onChange(e.target.value)} className="h-16 w-16 -translate-x-3 -translate-y-3 cursor-pointer opacity-0"/></span>{label}</label>}
function Toggle({label,value,onChange}:{label:string;value:boolean;onChange:(v:boolean)=>void}){return <button onClick={()=>onChange(!value)} className="flex w-full items-center justify-between rounded-2xl px-4 py-3 text-sm text-slate-300"><span>{label}</span><span className={`relative h-6 w-11 rounded-full transition ${value?"bg-[#0077c8]":"bg-white/10"}`}><span className={`absolute top-1 size-4 rounded-full bg-white transition ${value?"left-6":"left-1"}`}/></span></button>}
